baseURL: https://pesuruhjayasumpahkuantan.netlify.app/
title: pesuruhjaya sumpah kuantan
theme: hugo-coder
languageCode: ms
defaultContentLanguage: ms
paginate: 20
enableEmoji: yes
markup:
  highlight:
    noClasses: no
params:
  author: Tengku Hanim Syamimi Bt Tengku Mokhtar
  avatarURL: images/avatar4.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: pesuruhjaya sumpah kuantan's website
  hideColorSchemeToggle: no
  info:
    - Oath Comissioner 
    - Kuantan, Tanjung Lumpur and Inderapura
  keywords: blog,developer,personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2023
  social:
    - icon: fa fa-3x fa-facebook
      name: Facebook
      url: https://www.facebook.com/profile.php?id=100090009496211
      weight: 1
    - icon: fa fa-3x fa-instagram
      name: Instagram
      url: https://www.instagram.com/pesuruhjayasumpah_tglumpur/
      weight: 2
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: 'English'
    menu:
      main:
        - name: Services
          url: services/
          weight: 1
        - name: About me
          url: about/
          weight: 2
        - name: Contact me
          url: contact/
          weight: 3
  ms:
    languageName: 'Bahasa Melayu'
    menu:
      main:
        - name: Perkhidmatan
          url: services/
          weight: 1
        - name: Tentang saya
          url: about/
          weight: 2
        - name: Hubungi saya
          url: contact/
          weight: 3
    params:
      author: Tengku Hanim Syamimi Bt Tengku Mokhtar
      description: Pesuruhjaya Sumpah
      info: 
      - Pesuruhjaya Sumpah 
      - Kuantan, Tanjung Lumpur dan Inderapura
      keywords: pesuruhjaya sumpah, kuantan, tanjung lumpur, inderapura
    title: Pesuruhjaya Sumpah Kuantan
